name: Destroy AWS Resources

on:
  workflow_dispatch: # This adds the "Run workflow" button in GitHub

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Scale down ECS Service
        run: |
          aws ecs update-service --cluster nodebase-cluster --service nodebase-service --desired-count 0

      - name: Stop RDS Instance (Saves money without deleting data)
        run: |
          aws rds stop-db-instance --db-instance-identifier nodebase-db